const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const port = 5000;
const app = express();
const token = 'hFT4yc823l5dJ5QYvY84B4fjUh3HmTVfidjrf9kr9Q8cL88mW2F4dSDejEn5nP5oyeU2rPWUIt5l88O7';

let nextId = 6;

let pokemon = [
        {
          "ID": 1,
          "Name": "Bulbasaur",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 318,
          "HP": 45,
          "Attack": 49,
          "Defense": 49,
          "Sp Atk": 65,
          "Sp Def": 65,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 2,
          "Name": "Ivysaur",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 405,
          "HP": 60,
          "Attack": 62,
          "Defense": 63,
          "Sp Atk": 80,
          "Sp Def": 80,
          "Speed": 60,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 3,
          "Name": "Venusaur",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 525,
          "HP": 80,
          "Attack": 82,
          "Defense": 83,
          "Sp Atk": 100,
          "Sp Def": 100,
          "Speed": 80,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 3,
          "Name": "VenusaurMega Venusaur",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 625,
          "HP": 80,
          "Attack": 100,
          "Defense": 123,
          "Sp Atk": 122,
          "Sp Def": 120,
          "Speed": 80,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 4,
          "Name": "Charmander",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 309,
          "HP": 39,
          "Attack": 52,
          "Defense": 43,
          "Sp Atk": 60,
          "Sp Def": 50,
          "Speed": 65,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 5,
          "Name": "Charmeleon",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 405,
          "HP": 58,
          "Attack": 64,
          "Defense": 58,
          "Sp Atk": 80,
          "Sp Def": 65,
          "Speed": 80,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 6,
          "Name": "Charizard",
          "Type 1": "Fire",
          "Type 2": "Flying",
          "Total": 534,
          "HP": 78,
          "Attack": 84,
          "Defense": 78,
          "Sp Atk": 109,
          "Sp Def": 85,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 6,
          "Name": "CharizardMega Charizard X",
          "Type 1": "Fire",
          "Type 2": "Dragon",
          "Total": 634,
          "HP": 78,
          "Attack": 130,
          "Defense": 111,
          "Sp Atk": 130,
          "Sp Def": 85,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 6,
          "Name": "CharizardMega Charizard Y",
          "Type 1": "Fire",
          "Type 2": "Flying",
          "Total": 634,
          "HP": 78,
          "Attack": 104,
          "Defense": 78,
          "Sp Atk": 159,
          "Sp Def": 115,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 7,
          "Name": "Squirtle",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 314,
          "HP": 44,
          "Attack": 48,
          "Defense": 65,
          "Sp Atk": 50,
          "Sp Def": 64,
          "Speed": 43,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 8,
          "Name": "Wartortle",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 405,
          "HP": 59,
          "Attack": 63,
          "Defense": 80,
          "Sp Atk": 65,
          "Sp Def": 80,
          "Speed": 58,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 9,
          "Name": "Blastoise",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 530,
          "HP": 79,
          "Attack": 83,
          "Defense": 100,
          "Sp Atk": 85,
          "Sp Def": 105,
          "Speed": 78,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 9,
          "Name": "BlastoiseMega Blastoise",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 630,
          "HP": 79,
          "Attack": 103,
          "Defense": 120,
          "Sp Atk": 135,
          "Sp Def": 115,
          "Speed": 78,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 10,
          "Name": "Caterpie",
          "Type 1": "Bug",
          "Type 2": "",
          "Total": 195,
          "HP": 45,
          "Attack": 30,
          "Defense": 35,
          "Sp Atk": 20,
          "Sp Def": 20,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 11,
          "Name": "Metapod",
          "Type 1": "Bug",
          "Type 2": "",
          "Total": 205,
          "HP": 50,
          "Attack": 20,
          "Defense": 55,
          "Sp Atk": 25,
          "Sp Def": 25,
          "Speed": 30,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 12,
          "Name": "Butterfree",
          "Type 1": "Bug",
          "Type 2": "Flying",
          "Total": 395,
          "HP": 60,
          "Attack": 45,
          "Defense": 50,
          "Sp Atk": 90,
          "Sp Def": 80,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 13,
          "Name": "Weedle",
          "Type 1": "Bug",
          "Type 2": "Poison",
          "Total": 195,
          "HP": 40,
          "Attack": 35,
          "Defense": 30,
          "Sp Atk": 20,
          "Sp Def": 20,
          "Speed": 50,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 14,
          "Name": "Kakuna",
          "Type 1": "Bug",
          "Type 2": "Poison",
          "Total": 205,
          "HP": 45,
          "Attack": 25,
          "Defense": 50,
          "Sp Atk": 25,
          "Sp Def": 25,
          "Speed": 35,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 15,
          "Name": "Beedrill",
          "Type 1": "Bug",
          "Type 2": "Poison",
          "Total": 395,
          "HP": 65,
          "Attack": 90,
          "Defense": 40,
          "Sp Atk": 45,
          "Sp Def": 80,
          "Speed": 75,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 15,
          "Name": "BeedrillMega Beedrill",
          "Type 1": "Bug",
          "Type 2": "Poison",
          "Total": 495,
          "HP": 65,
          "Attack": 150,
          "Defense": 40,
          "Sp Atk": 15,
          "Sp Def": 80,
          "Speed": 145,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 16,
          "Name": "Pidgey",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 251,
          "HP": 40,
          "Attack": 45,
          "Defense": 40,
          "Sp Atk": 35,
          "Sp Def": 35,
          "Speed": 56,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 17,
          "Name": "Pidgeotto",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 349,
          "HP": 63,
          "Attack": 60,
          "Defense": 55,
          "Sp Atk": 50,
          "Sp Def": 50,
          "Speed": 71,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 18,
          "Name": "Pidgeot",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 479,
          "HP": 83,
          "Attack": 80,
          "Defense": 75,
          "Sp Atk": 70,
          "Sp Def": 70,
          "Speed": 101,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 18,
          "Name": "PidgeotMega Pidgeot",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 579,
          "HP": 83,
          "Attack": 80,
          "Defense": 80,
          "Sp Atk": 135,
          "Sp Def": 80,
          "Speed": 121,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 19,
          "Name": "Rattata",
          "Type 1": "Normal",
          "Type 2": "",
          "Total": 253,
          "HP": 30,
          "Attack": 56,
          "Defense": 35,
          "Sp Atk": 25,
          "Sp Def": 35,
          "Speed": 72,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 20,
          "Name": "Raticate",
          "Type 1": "Normal",
          "Type 2": "",
          "Total": 413,
          "HP": 55,
          "Attack": 81,
          "Defense": 60,
          "Sp Atk": 50,
          "Sp Def": 70,
          "Speed": 97,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 21,
          "Name": "Spearow",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 262,
          "HP": 40,
          "Attack": 60,
          "Defense": 30,
          "Sp Atk": 31,
          "Sp Def": 31,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 22,
          "Name": "Fearow",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 442,
          "HP": 65,
          "Attack": 90,
          "Defense": 65,
          "Sp Atk": 61,
          "Sp Def": 61,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 23,
          "Name": "Ekans",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 288,
          "HP": 35,
          "Attack": 60,
          "Defense": 44,
          "Sp Atk": 40,
          "Sp Def": 54,
          "Speed": 55,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 24,
          "Name": "Arbok",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 438,
          "HP": 60,
          "Attack": 85,
          "Defense": 69,
          "Sp Atk": 65,
          "Sp Def": 79,
          "Speed": 80,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 25,
          "Name": "Pikachu",
          "Type 1": "Electric",
          "Type 2": "",
          "Total": 320,
          "HP": 35,
          "Attack": 55,
          "Defense": 40,
          "Sp Atk": 50,
          "Sp Def": 50,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 26,
          "Name": "Raichu",
          "Type 1": "Electric",
          "Type 2": "",
          "Total": 485,
          "HP": 60,
          "Attack": 90,
          "Defense": 55,
          "Sp Atk": 90,
          "Sp Def": 80,
          "Speed": 110,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 27,
          "Name": "Sandshrew",
          "Type 1": "Ground",
          "Type 2": "",
          "Total": 300,
          "HP": 50,
          "Attack": 75,
          "Defense": 85,
          "Sp Atk": 20,
          "Sp Def": 30,
          "Speed": 40,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 28,
          "Name": "Sandslash",
          "Type 1": "Ground",
          "Type 2": "",
          "Total": 450,
          "HP": 75,
          "Attack": 100,
          "Defense": 110,
          "Sp Atk": 45,
          "Sp Def": 55,
          "Speed": 65,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 29,
          "Name": "Nidoran♀",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 275,
          "HP": 55,
          "Attack": 47,
          "Defense": 52,
          "Sp Atk": 40,
          "Sp Def": 40,
          "Speed": 41,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 30,
          "Name": "Nidorina",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 365,
          "HP": 70,
          "Attack": 62,
          "Defense": 67,
          "Sp Atk": 55,
          "Sp Def": 55,
          "Speed": 56,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 31,
          "Name": "Nidoqueen",
          "Type 1": "Poison",
          "Type 2": "Ground",
          "Total": 505,
          "HP": 90,
          "Attack": 92,
          "Defense": 87,
          "Sp Atk": 75,
          "Sp Def": 85,
          "Speed": 76,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 32,
          "Name": "Nidoran♂",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 273,
          "HP": 46,
          "Attack": 57,
          "Defense": 40,
          "Sp Atk": 40,
          "Sp Def": 40,
          "Speed": 50,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 33,
          "Name": "Nidorino",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 365,
          "HP": 61,
          "Attack": 72,
          "Defense": 57,
          "Sp Atk": 55,
          "Sp Def": 55,
          "Speed": 65,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 34,
          "Name": "Nidoking",
          "Type 1": "Poison",
          "Type 2": "Ground",
          "Total": 505,
          "HP": 81,
          "Attack": 102,
          "Defense": 77,
          "Sp Atk": 85,
          "Sp Def": 75,
          "Speed": 85,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 35,
          "Name": "Clefairy",
          "Type 1": "Fairy",
          "Type 2": "",
          "Total": 323,
          "HP": 70,
          "Attack": 45,
          "Defense": 48,
          "Sp Atk": 60,
          "Sp Def": 65,
          "Speed": 35,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 36,
          "Name": "Clefable",
          "Type 1": "Fairy",
          "Type 2": "",
          "Total": 483,
          "HP": 95,
          "Attack": 70,
          "Defense": 73,
          "Sp Atk": 95,
          "Sp Def": 90,
          "Speed": 60,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 37,
          "Name": "Vulpix",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 299,
          "HP": 38,
          "Attack": 41,
          "Defense": 40,
          "Sp Atk": 50,
          "Sp Def": 65,
          "Speed": 65,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 38,
          "Name": "Ninetales",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 505,
          "HP": 73,
          "Attack": 76,
          "Defense": 75,
          "Sp Atk": 81,
          "Sp Def": 100,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 39,
          "Name": "Jigglypuff",
          "Type 1": "Normal",
          "Type 2": "Fairy",
          "Total": 270,
          "HP": 115,
          "Attack": 45,
          "Defense": 20,
          "Sp Atk": 45,
          "Sp Def": 25,
          "Speed": 20,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 40,
          "Name": "Wigglytuff",
          "Type 1": "Normal",
          "Type 2": "Fairy",
          "Total": 435,
          "HP": 140,
          "Attack": 70,
          "Defense": 45,
          "Sp Atk": 85,
          "Sp Def": 50,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 41,
          "Name": "Zubat",
          "Type 1": "Poison",
          "Type 2": "Flying",
          "Total": 245,
          "HP": 40,
          "Attack": 45,
          "Defense": 35,
          "Sp Atk": 30,
          "Sp Def": 40,
          "Speed": 55,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 42,
          "Name": "Golbat",
          "Type 1": "Poison",
          "Type 2": "Flying",
          "Total": 455,
          "HP": 75,
          "Attack": 80,
          "Defense": 70,
          "Sp Atk": 65,
          "Sp Def": 75,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 43,
          "Name": "Oddish",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 320,
          "HP": 45,
          "Attack": 50,
          "Defense": 55,
          "Sp Atk": 75,
          "Sp Def": 65,
          "Speed": 30,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 44,
          "Name": "Gloom",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 395,
          "HP": 60,
          "Attack": 65,
          "Defense": 70,
          "Sp Atk": 85,
          "Sp Def": 75,
          "Speed": 40,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 45,
          "Name": "Vileplume",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 490,
          "HP": 75,
          "Attack": 80,
          "Defense": 85,
          "Sp Atk": 110,
          "Sp Def": 90,
          "Speed": 50,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 46,
          "Name": "Paras",
          "Type 1": "Bug",
          "Type 2": "Grass",
          "Total": 285,
          "HP": 35,
          "Attack": 70,
          "Defense": 55,
          "Sp Atk": 45,
          "Sp Def": 55,
          "Speed": 25,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 47,
          "Name": "Parasect",
          "Type 1": "Bug",
          "Type 2": "Grass",
          "Total": 405,
          "HP": 60,
          "Attack": 95,
          "Defense": 80,
          "Sp Atk": 60,
          "Sp Def": 80,
          "Speed": 30,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 48,
          "Name": "Venonat",
          "Type 1": "Bug",
          "Type 2": "Poison",
          "Total": 305,
          "HP": 60,
          "Attack": 55,
          "Defense": 50,
          "Sp Atk": 40,
          "Sp Def": 55,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 49,
          "Name": "Venomoth",
          "Type 1": "Bug",
          "Type 2": "Poison",
          "Total": 450,
          "HP": 70,
          "Attack": 65,
          "Defense": 60,
          "Sp Atk": 90,
          "Sp Def": 75,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 50,
          "Name": "Diglett",
          "Type 1": "Ground",
          "Type 2": "",
          "Total": 265,
          "HP": 10,
          "Attack": 55,
          "Defense": 25,
          "Sp Atk": 35,
          "Sp Def": 45,
          "Speed": 95,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 51,
          "Name": "Dugtrio",
          "Type 1": "Ground",
          "Type 2": "",
          "Total": 405,
          "HP": 35,
          "Attack": 80,
          "Defense": 50,
          "Sp Atk": 50,
          "Sp Def": 70,
          "Speed": 120,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 52,
          "Name": "Meowth",
          "Type 1": "Normal",
          "Type 2": "",
          "Total": 290,
          "HP": 40,
          "Attack": 45,
          "Defense": 35,
          "Sp Atk": 40,
          "Sp Def": 40,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 53,
          "Name": "Persian",
          "Type 1": "Normal",
          "Type 2": "",
          "Total": 440,
          "HP": 65,
          "Attack": 70,
          "Defense": 60,
          "Sp Atk": 65,
          "Sp Def": 65,
          "Speed": 115,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 54,
          "Name": "Psyduck",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 320,
          "HP": 50,
          "Attack": 52,
          "Defense": 48,
          "Sp Atk": 65,
          "Sp Def": 50,
          "Speed": 55,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 55,
          "Name": "Golduck",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 500,
          "HP": 80,
          "Attack": 82,
          "Defense": 78,
          "Sp Atk": 95,
          "Sp Def": 80,
          "Speed": 85,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 56,
          "Name": "Mankey",
          "Type 1": "Fighting",
          "Type 2": "",
          "Total": 305,
          "HP": 40,
          "Attack": 80,
          "Defense": 35,
          "Sp Atk": 35,
          "Sp Def": 45,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 57,
          "Name": "Primeape",
          "Type 1": "Fighting",
          "Type 2": "",
          "Total": 455,
          "HP": 65,
          "Attack": 105,
          "Defense": 60,
          "Sp Atk": 60,
          "Sp Def": 70,
          "Speed": 95,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 58,
          "Name": "Growlithe",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 350,
          "HP": 55,
          "Attack": 70,
          "Defense": 45,
          "Sp Atk": 70,
          "Sp Def": 50,
          "Speed": 60,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 59,
          "Name": "Arcanine",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 555,
          "HP": 90,
          "Attack": 110,
          "Defense": 80,
          "Sp Atk": 100,
          "Sp Def": 80,
          "Speed": 95,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 60,
          "Name": "Poliwag",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 300,
          "HP": 40,
          "Attack": 50,
          "Defense": 40,
          "Sp Atk": 40,
          "Sp Def": 40,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 61,
          "Name": "Poliwhirl",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 385,
          "HP": 65,
          "Attack": 65,
          "Defense": 65,
          "Sp Atk": 50,
          "Sp Def": 50,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 62,
          "Name": "Poliwrath",
          "Type 1": "Water",
          "Type 2": "Fighting",
          "Total": 510,
          "HP": 90,
          "Attack": 95,
          "Defense": 95,
          "Sp Atk": 70,
          "Sp Def": 90,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 63,
          "Name": "Abra",
          "Type 1": "Psychic",
          "Type 2": "",
          "Total": 310,
          "HP": 25,
          "Attack": 20,
          "Defense": 15,
          "Sp Atk": 105,
          "Sp Def": 55,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 64,
          "Name": "Kadabra",
          "Type 1": "Psychic",
          "Type 2": "",
          "Total": 400,
          "HP": 40,
          "Attack": 35,
          "Defense": 30,
          "Sp Atk": 120,
          "Sp Def": 70,
          "Speed": 105,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 65,
          "Name": "Alakazam",
          "Type 1": "Psychic",
          "Type 2": "",
          "Total": 500,
          "HP": 55,
          "Attack": 50,
          "Defense": 45,
          "Sp Atk": 135,
          "Sp Def": 95,
          "Speed": 120,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 65,
          "Name": "AlakazamMega Alakazam",
          "Type 1": "Psychic",
          "Type 2": "",
          "Total": 590,
          "HP": 55,
          "Attack": 50,
          "Defense": 65,
          "Sp Atk": 175,
          "Sp Def": 95,
          "Speed": 150,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 66,
          "Name": "Machop",
          "Type 1": "Fighting",
          "Type 2": "",
          "Total": 305,
          "HP": 70,
          "Attack": 80,
          "Defense": 50,
          "Sp Atk": 35,
          "Sp Def": 35,
          "Speed": 35,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 67,
          "Name": "Machoke",
          "Type 1": "Fighting",
          "Type 2": "",
          "Total": 405,
          "HP": 80,
          "Attack": 100,
          "Defense": 70,
          "Sp Atk": 50,
          "Sp Def": 60,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 68,
          "Name": "Machamp",
          "Type 1": "Fighting",
          "Type 2": "",
          "Total": 505,
          "HP": 90,
          "Attack": 130,
          "Defense": 80,
          "Sp Atk": 65,
          "Sp Def": 85,
          "Speed": 55,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 69,
          "Name": "Bellsprout",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 300,
          "HP": 50,
          "Attack": 75,
          "Defense": 35,
          "Sp Atk": 70,
          "Sp Def": 30,
          "Speed": 40,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 70,
          "Name": "Weepinbell",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 390,
          "HP": 65,
          "Attack": 90,
          "Defense": 50,
          "Sp Atk": 85,
          "Sp Def": 45,
          "Speed": 55,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 71,
          "Name": "Victreebel",
          "Type 1": "Grass",
          "Type 2": "Poison",
          "Total": 490,
          "HP": 80,
          "Attack": 105,
          "Defense": 65,
          "Sp Atk": 100,
          "Sp Def": 70,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 72,
          "Name": "Tentacool",
          "Type 1": "Water",
          "Type 2": "Poison",
          "Total": 335,
          "HP": 40,
          "Attack": 40,
          "Defense": 35,
          "Sp Atk": 50,
          "Sp Def": 100,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 73,
          "Name": "Tentacruel",
          "Type 1": "Water",
          "Type 2": "Poison",
          "Total": 515,
          "HP": 80,
          "Attack": 70,
          "Defense": 65,
          "Sp Atk": 80,
          "Sp Def": 120,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 74,
          "Name": "Geodude",
          "Type 1": "Rock",
          "Type 2": "Ground",
          "Total": 300,
          "HP": 40,
          "Attack": 80,
          "Defense": 100,
          "Sp Atk": 30,
          "Sp Def": 30,
          "Speed": 20,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 75,
          "Name": "Graveler",
          "Type 1": "Rock",
          "Type 2": "Ground",
          "Total": 390,
          "HP": 55,
          "Attack": 95,
          "Defense": 115,
          "Sp Atk": 45,
          "Sp Def": 45,
          "Speed": 35,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 76,
          "Name": "Golem",
          "Type 1": "Rock",
          "Type 2": "Ground",
          "Total": 495,
          "HP": 80,
          "Attack": 120,
          "Defense": 130,
          "Sp Atk": 55,
          "Sp Def": 65,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 77,
          "Name": "Ponyta",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 410,
          "HP": 50,
          "Attack": 85,
          "Defense": 55,
          "Sp Atk": 65,
          "Sp Def": 65,
          "Speed": 90,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 78,
          "Name": "Rapidash",
          "Type 1": "Fire",
          "Type 2": "",
          "Total": 500,
          "HP": 65,
          "Attack": 100,
          "Defense": 70,
          "Sp Atk": 80,
          "Sp Def": 80,
          "Speed": 105,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 79,
          "Name": "Slowpoke",
          "Type 1": "Water",
          "Type 2": "Psychic",
          "Total": 315,
          "HP": 90,
          "Attack": 65,
          "Defense": 65,
          "Sp Atk": 40,
          "Sp Def": 40,
          "Speed": 15,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 80,
          "Name": "Slowbro",
          "Type 1": "Water",
          "Type 2": "Psychic",
          "Total": 490,
          "HP": 95,
          "Attack": 75,
          "Defense": 110,
          "Sp Atk": 100,
          "Sp Def": 80,
          "Speed": 30,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 80,
          "Name": "SlowbroMega Slowbro",
          "Type 1": "Water",
          "Type 2": "Psychic",
          "Total": 590,
          "HP": 95,
          "Attack": 75,
          "Defense": 180,
          "Sp Atk": 130,
          "Sp Def": 80,
          "Speed": 30,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 81,
          "Name": "Magnemite",
          "Type 1": "Electric",
          "Type 2": "Steel",
          "Total": 325,
          "HP": 25,
          "Attack": 35,
          "Defense": 70,
          "Sp Atk": 95,
          "Sp Def": 55,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 82,
          "Name": "Magneton",
          "Type 1": "Electric",
          "Type 2": "Steel",
          "Total": 465,
          "HP": 50,
          "Attack": 60,
          "Defense": 95,
          "Sp Atk": 120,
          "Sp Def": 70,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 83,
          "Name": "Farfetch'd",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 352,
          "HP": 52,
          "Attack": 65,
          "Defense": 55,
          "Sp Atk": 58,
          "Sp Def": 62,
          "Speed": 60,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 84,
          "Name": "Doduo",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 310,
          "HP": 35,
          "Attack": 85,
          "Defense": 45,
          "Sp Atk": 35,
          "Sp Def": 35,
          "Speed": 75,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 85,
          "Name": "Dodrio",
          "Type 1": "Normal",
          "Type 2": "Flying",
          "Total": 460,
          "HP": 60,
          "Attack": 110,
          "Defense": 70,
          "Sp Atk": 60,
          "Sp Def": 60,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 86,
          "Name": "Seel",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 325,
          "HP": 65,
          "Attack": 45,
          "Defense": 55,
          "Sp Atk": 45,
          "Sp Def": 70,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 87,
          "Name": "Dewgong",
          "Type 1": "Water",
          "Type 2": "Ice",
          "Total": 475,
          "HP": 90,
          "Attack": 70,
          "Defense": 80,
          "Sp Atk": 70,
          "Sp Def": 95,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 88,
          "Name": "Grimer",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 325,
          "HP": 80,
          "Attack": 80,
          "Defense": 50,
          "Sp Atk": 40,
          "Sp Def": 50,
          "Speed": 25,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 89,
          "Name": "Muk",
          "Type 1": "Poison",
          "Type 2": "",
          "Total": 500,
          "HP": 105,
          "Attack": 105,
          "Defense": 75,
          "Sp Atk": 65,
          "Sp Def": 100,
          "Speed": 50,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 90,
          "Name": "Shellder",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 305,
          "HP": 30,
          "Attack": 65,
          "Defense": 100,
          "Sp Atk": 45,
          "Sp Def": 25,
          "Speed": 40,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 91,
          "Name": "Cloyster",
          "Type 1": "Water",
          "Type 2": "Ice",
          "Total": 525,
          "HP": 50,
          "Attack": 95,
          "Defense": 180,
          "Sp Atk": 85,
          "Sp Def": 45,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 92,
          "Name": "Gastly",
          "Type 1": "Ghost",
          "Type 2": "Poison",
          "Total": 310,
          "HP": 30,
          "Attack": 35,
          "Defense": 30,
          "Sp Atk": 100,
          "Sp Def": 35,
          "Speed": 80,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 93,
          "Name": "Haunter",
          "Type 1": "Ghost",
          "Type 2": "Poison",
          "Total": 405,
          "HP": 45,
          "Attack": 50,
          "Defense": 45,
          "Sp Atk": 115,
          "Sp Def": 55,
          "Speed": 95,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 94,
          "Name": "Gengar",
          "Type 1": "Ghost",
          "Type 2": "Poison",
          "Total": 500,
          "HP": 60,
          "Attack": 65,
          "Defense": 60,
          "Sp Atk": 130,
          "Sp Def": 75,
          "Speed": 110,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 94,
          "Name": "GengarMega Gengar",
          "Type 1": "Ghost",
          "Type 2": "Poison",
          "Total": 600,
          "HP": 60,
          "Attack": 65,
          "Defense": 80,
          "Sp Atk": 170,
          "Sp Def": 95,
          "Speed": 130,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 95,
          "Name": "Onix",
          "Type 1": "Rock",
          "Type 2": "Ground",
          "Total": 385,
          "HP": 35,
          "Attack": 45,
          "Defense": 160,
          "Sp Atk": 30,
          "Sp Def": 45,
          "Speed": 70,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 96,
          "Name": "Drowzee",
          "Type 1": "Psychic",
          "Type 2": "",
          "Total": 328,
          "HP": 60,
          "Attack": 48,
          "Defense": 45,
          "Sp Atk": 43,
          "Sp Def": 90,
          "Speed": 42,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 97,
          "Name": "Hypno",
          "Type 1": "Psychic",
          "Type 2": "",
          "Total": 483,
          "HP": 85,
          "Attack": 73,
          "Defense": 70,
          "Sp Atk": 73,
          "Sp Def": 115,
          "Speed": 67,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 98,
          "Name": "Krabby",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 325,
          "HP": 30,
          "Attack": 105,
          "Defense": 90,
          "Sp Atk": 25,
          "Sp Def": 25,
          "Speed": 50,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 99,
          "Name": "Kingler",
          "Type 1": "Water",
          "Type 2": "",
          "Total": 475,
          "HP": 55,
          "Attack": 130,
          "Defense": 115,
          "Sp Atk": 50,
          "Sp Def": 50,
          "Speed": 75,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 100,
          "Name": "Voltorb",
          "Type 1": "Electric",
          "Type 2": "",
          "Total": 330,
          "HP": 40,
          "Attack": 30,
          "Defense": 50,
          "Sp Atk": 55,
          "Sp Def": 55,
          "Speed": 100,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 101,
          "Name": "Electrode",
          "Type 1": "Electric",
          "Type 2": "",
          "Total": 480,
          "HP": 60,
          "Attack": 50,
          "Defense": 70,
          "Sp Atk": 80,
          "Sp Def": 80,
          "Speed": 140,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 102,
          "Name": "Exeggcute",
          "Type 1": "Grass",
          "Type 2": "Psychic",
          "Total": 325,
          "HP": 60,
          "Attack": 40,
          "Defense": 80,
          "Sp Atk": 60,
          "Sp Def": 45,
          "Speed": 40,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 103,
          "Name": "Exeggutor",
          "Type 1": "Grass",
          "Type 2": "Psychic",
          "Total": 520,
          "HP": 95,
          "Attack": 95,
          "Defense": 85,
          "Sp Atk": 125,
          "Sp Def": 65,
          "Speed": 55,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 104,
          "Name": "Cubone",
          "Type 1": "Ground",
          "Type 2": "",
          "Total": 320,
          "HP": 50,
          "Attack": 50,
          "Defense": 95,
          "Sp Atk": 40,
          "Sp Def": 50,
          "Speed": 35,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 105,
          "Name": "Marowak",
          "Type 1": "Ground",
          "Type 2": "",
          "Total": 425,
          "HP": 60,
          "Attack": 80,
          "Defense": 110,
          "Sp Atk": 50,
          "Sp Def": 80,
          "Speed": 45,
          "Generation": 1,
          "Legendary": false
        },
        {
          "ID": 106,
          "Name": "Hitmonlee",
          "Type 1": "Fighting",
          "Type 2": "",
          "Total": 455,
          "HP": 50,
          "Attack": 120,
          "Defense": 53,
          "Sp Atk": 35,
          "Sp Def": 110,
          "Speed": 87,
          "Generation": 1,
          "Legendary": false
        }
];

app.use(bodyParser.json());

app.use(cors());

function authenticator(req, res, next) {
  const { authorization } = req.headers;
  if (authorization === token) {
    next();
  } else {
    res.status(403).json({ error: 'User be logged in to do that.' });
  }
}

app.post('/api/login', (req, res) => {
  const { username, password } = req.body;
  if (username === 'Pokemon Master' && password === 'ash') {
    req.loggedIn = true;
    res.status(200).json({
      payload: token
    });
  } else {
    res
      .status(403)
      .json({ error: 'Username or Password incorrect. Please see Readme' });
  }
});

app.get('/api/pokemon', authenticator, (req, res) => {
  setTimeout(() => {
    res.send(pokemon);
  }, 1000);
});

app.get('/api/pokemon/:id', authenticator, (req, res) => {
  const pokemon = pokemon.find(f => f.id == req.params.id);

  if (pokemon) {
    res.status(200).json(pokemon);
  } else {
    res.status(404).send({ msg: 'Pokemon not found' });
  }
});

app.post('/api/pokemon', authenticator, (req, res) => {
  const pokemon = { id: getNextId(), ...req.body };

  pokemon = [...pokemon, pokemon];

  res.send(pokemon);
});

app.put('/api/pokemon/:id', authenticator, (req, res) => {
  const { id } = req.params;

  const pokemonIndex = pokemon.findIndex(f => f.id == id);

  if (pokemonIndex > -1) {
    const pokemon = { ...pokemon[pokemonIndex], ...req.body };

    pokemon = [
      ...pokemon.slice(0, pokemonIndex),
      pokemon,
      ...pokemon.slice(pokemonIndex + 1)
    ];
    res.send(pokemon);
  } else {
    res.status(404).send({ msg: 'Pokemon not found' });
  }
});

app.delete('/api/pokemon/:id', authenticator, (req, res) => {
  const { id } = req.params;

  pokemon = pokemon.filter(f => f.id !== Number(id));

  res.send(pokemon);
});

function getNextId() {
  return ++nextId;
}

app.listen(port, () => {
  console.log(`server listening on port ${port}`);
});
